main: ink.anh.lingo.AnhyLingo
name: AnhyLingo
version: 0.1
author: AnhyDev
api-version: 1.13
description: AnhyLingo projekt
website: http://dev.anh.ink/anhylingo
commands:
    lingo:
        aliases: [anhylingo]
        usage: "[AnhyLingo] TThe command '/lingo (/anhylingo)' execution error, please check the arguments' correctness."