main: ink.anh.lingo.AnhyLingo
name: AnhyLingo
version: 0.0.1
author: AnhyDev
api-version: 1.19
description: AnhyLingo projekt
website: http://anh.ink
commands:
    lingo:
        aliases: [anhylingo]
        usage: "The command '/lingo (/itemlingo)' execution error, please check the arguments' correctness."